apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: sample-app-template
  title: Create a health sample application with a CI pipeline
  description: Create a starter application with a CI pipeline
  tags:
    - recommended
spec:
  owner: skitamura7446
  system: sample-system
  type: service

  parameters:
    - title: Provide information about the new component
      required:
        - org_name
        - app_name
        - owner
        - system
      properties:
        org_name:
          title: Organization Name
          type: string
        app_name:
          title: Repository Name
          type: string
          default: "health-sample"
        description:
          title: Description
          type: string
          description: Help others understand what this component is for
        owner:
          title: Owner
          type: string
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              kind:
                - Group
                - User
        system:
          title: System
          type: string
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              kind:
                - System
  
  steps:
    - id: sourcecode_template
      name: Generating the Source Code Component
      action: fetch:template
      input:
        url: ./app-skeleton
        values:
          org_name: ${{ parameters.org_name }}
          app_name: ${{ parameters.app_name }}
          owner: ${{ parameters.owner }}
          system: ${{ parameters.system }}
          description: ${{ parameters.description }}
        targetPath: ./tenant-app

    - id: publish-app
      name: Publish App Repository
      action: publish:github
      input:
        allowedHosts: ['github.com']
        repoUrl: github.com?owner=${{ parameters.org_name }}&repo=${{ parameters.app_name }}-app
        repoVisibility: public
        sourcePath: ./tenant-app
        defaultBranch: develop
        protectDefaultBranch: false

    - id: register
      name: Registering the Catalog Info Component
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish-app'].output.repoContentsUrl }}
        catalogInfoPath: "/catalog-info.yaml"

    - id: manifest_template
      name: Generating the CI Component
      action: fetch:template
      input:
        url: ./manifest-skeleton 
        copyWithoutTemplating:
          - .github/workflows/
        values:
          org_name: ${{ parameters.org_name }}
          app_name: ${{ parameters.app_name }}
          owner: ${{ parameters.owner }}
          system: ${{ parameters.system }}
          description: ${{ parameters.description }}
        targetPath: ./tenant-manifest

    - id: publish-manifest
      name: Publish Manifest Repository
      action: publish:github
      input:
        allowedHosts: ['github.com']
        repoUrl: github.com?owner=${{ parameters.org_name }}&repo=${{ parameters.app_name }}-manifest
        repoVisibility: public
        sourcePath: ./tenant-manifest
        defaultBranch: develop
        protectDefaultBranch: false

    - id: create-argocd-resources
      name: Create ArgoCD Resources
      action: argocd:create-resources
      input:
        appName: ${{ parameters.app_name }}-bootstrap
        argoInstance: main
        namespace: openshift-gitops
        repoUrl: https://github.com/${{ parameters.org_name }}/${{ parameters.app_name }}-manifest.git
        path: 'argocd/'

  output:
    links:
      - title: Open the Source Code Repository
        url: ${{ steps.publish-app.output.remoteUrl }}
      - title: Open the Catalog Info Component
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
