apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.app_name }}
  {%- if values.description %}
  description: ${{ values.description }}
  {%- endif %}
  annotations:
    argocd/app-name: ${{ values.app_name }}
    tektonci/build-namespace: ${{ values.app_name }}-develop
    backstage.io/kubernetes-id: ${{ values.app_name }}
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: ${{ values.org_name }}/${{ values.app_name }}
spec:
  type: service 
  system: ${{ values.system }}
  lifecycle: production
  owner: ${{ values.owner }}
