apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.app_name }}
  {%- if values.description %}
  description: ${{ values.description }}
  {%- endif %}
  annotations:
    argocd/app-name: ${{ values.app_name }}-dev
    tektonci/build-namespace: ${{ values.app_name }}-develop
    backstage.io/kubernetes-id: ${{ values.app_name }}
    janus-idp.io/tekton-enabled : 'true'
    janus-idp.io/tekton : ${{ values.app_name }}
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: ${{ values.git_owner_name }}/${{ values.app_name }}-app
    sonarqube.org/project-key: default
spec:
  type: service 
  system: ${{ values.system | dump }}
  lifecycle: production
  owner: ${{ values.owner | dump }}
  git: ${{ values.git }}
  git_host_url: ${{ values.git_host_url }}
  git_owner_name: ${{ values.git_owner_name }}
